# Setup
title:               Bumjun Park
tagline:             'Statistics Major @ University of Wisconsin-Madison'
description: '<p align = "center"><img src="/photo.png" alt="Personal Photo" style="height: 200px; width:200px;" align = center/></p> <p>An undergraduate Statistics major at the University of Wisconsin-Madison. Certificates in Mathematics and Economic Analytics</p>'
url:                 https://bpark67.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# description:...
# About/contact
author:
  name:              Bumjun Park
  url:               https://www.linkedin.com/in/bumjun-park-4b8398241/
  email:             bpark67@wisc.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics: UA-104156586-1
